language: node_js
node_js:
- '10.6.0'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'

sudo: false

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      before_deploy: npm install semantic-release @traverson/semantic-release-config --no-save
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
