language: node_js
node_js:
- '10.6.0'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'

sudo: false

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"

# Allow greenkeeper to commit package-lock.json via greenkeeper-lockfile.
# greenkeeper-lockfile-upload will run only on the first listed node_js version.
# We still explicitly skip all greenkeeper-lockfile related steps on Node.js
# versions 4-7 because the build for the first GK commit (that updates
# package.json) will fail on those versions in the greenkeeper-lockfile-update
# step.
before_install: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || npm install -g greenkeeper-lockfile'
install: npm install
before_script: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || greenkeeper-lockfile-update'
after_script: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || greenkeeper-lockfile-upload'

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      before_deploy: npm install @traverson/semantic-release-config --no-save
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
